name: Test k8s mode v5
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: pat2
    container:
      image: quay.io/ascend/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 30000
